# Generated by Django 4.1.2 on 2022-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='my_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
